server:
  port: 8761

spring:
  profiles: node1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  profiles: node2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/

#eureka:
#  client:
#    region: eu-west-1
#    preferSameZone: false
#    registerWithEureka: true
#    fetchRegistry: true
#    useDnsForFetchingServiceUrls: true
#    eurekaServerDNSName: eureka.internalpreopenp.com
#    eurekaServerPort: 8761
#    eurekaServerURLContext: eureka
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#  instance:
#    leaseRenewalIntervalInSeconds: 30
#