server:
  port: 8989

spring:
  application:
    name: zuul

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/

# Enables retry for failed requests (not working atm)
#zuul:
#  retryable: true
#
#ribbon:
#  MaxAutoRetries: 100
#  MaxAutoRetriesNextServer: 100
#  OkToRetryOnAllOperations: true
